# Generated by Django 5.2.8 on 2025-11-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_docente_correo_alter_curso_docente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
