# Generated by Django 5.2.8 on 2025-11-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_alter_docente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(default='correo@default.com', max_length=254),
        ),
    ]
