# Generated by Django 5.2.8 on 2025-11-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0004_alter_docente_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
