# Generated by Django 5.2.8 on 2025-11-27 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0006_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=50)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimiento', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('puntaje', models.FloatField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('pendiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.evaluacionpendiente')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.pregunta')),
            ],
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
