# Generated by Django 5.2.8 on 2025-11-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0007_evaluacion_evaluacionpendiente_historial_pregunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='docente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluacionpendiente',
            name='alumno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historial',
            name='alumno',
            field=models.CharField(max_length=50),
        ),
    ]
